- .travis.yml
- ext/faster_path/extconf.rb
- lib/faster_path/version.rb
- test/faster_path_test.rb
- test/relative_test.rb
Allow Rust code to compile with jRuby
> jRuby support

- .travis.yml
- README.md
- faster_path.gemspec
- lib/faster_path/optional/monkeypatches.rb
- lib/faster_path/version.rb
- test/absolute_test.rb
- test/monkeypatches/faster_path_test.rb
- test/refinements/absoulte_test.rb
- test/refinements/chop_basename_test.rb
- test/refinements/relative_test.rb
- test/test_helper.rb
Monkey-patch method fixed = 66% performance gain!
> Refinements and monkeypatches

- Cargo.lock
- Cargo.toml
- faster_path.gemspec
- lib/faster_path.rb
- lib/faster_path/optional/monkeypatches.rb
- lib/faster_path/optional/refinements.rb
- src/basename.rs
- src/lib.rs
- src/tools/chomp_pathish_regex.rs
- test/basename_test.rb
- test/benches/absolute_benchmark.rb
- test/benches/basename_benchmark.rb
- test/benches/chop_basename_benchmark.rb
- test/benches/relative_benchmark.rb
- test/refinements/basename_test.rb
- test/test_helper.rb
Code is written, not ready for use.  Safe for merge though.
> Placeholder implementation of basename

- README.md
- lib/faster_path/version.rb
- src/basename_for_chop.rs
- src/dirname_for_chop.rs
- src/lib.rs
- test/chop_basename_test.rb
Monkey-patches now work!
`Pathname#chop_basename` now faster by 66% in performance
Fixes #19
> Fix chop_basename compat

- README.md
Builds and tests fine with stable, so it can be documented like that :).
> Recommend installing Rust stable

- src/basename.rs
- test/basename_test.rb
> basename now works smoothly when given nil

- src/basename_for_chop.rs
- src/both_are_blank.rs
- src/dirname_for_chop.rs
- test/chop_basename_test.rb
> chop_basename safely takes nil value

- src/is_blank.rs
- test/blank_test.rb
> FasterPath.blank? accepts nil as true

- src/is_relative.rs
- test/relative_test.rb
> relative? returns false on nil

- src/is_absolute.rs
- test/absolute_test.rb
> absolute? returns false on nil

- src/is_directory.rs
- test/directory_test.rb
> directory? returns false on nil

- src/add_trailing_separator.rs
- test/add_trailing_separator_test.rb
> add_trailing_separator safely takes nil

- README.md
- lib/faster_path.rb
- lib/faster_path/version.rb
- test/basename_test.rb
Everything functions as before but now with much better performance
> FasterPath.basename with 75% performace gain

- README.md
- lib/faster_path.rb
- lib/faster_path/optional/monkeypatches.rb
- lib/faster_path/optional/refinements.rb
- src/extname.rs
- src/lib.rs
- test/benches/extname_benchmark.rb
- test/extname_test.rb
- test/refinements/extname_test.rb
Implementation of File#extname in rust https://github.com/danielpclark/faster_path/issues/30
> File#extname

- lib/faster_path.rb
- src/lib.rs
- src/rust_arch_bits.rs
> Methods for determining if Ruby & Rust are 32-bit or 64-bit

- Rakefile
- test/pbench/pbench.rb
- test/pbench/pbench_suite.rb
- test/pbench_test.rb
People will have different results on different computer systems.  The
new pbench benchmark suite is for people to be able to share what their
particular computer and programming languages are accomplishing.
rake pbench
Currently false Minitest numbers show up at the end.  When someone
gets a change perhaps we can fix this.  Maybe it's as simple as not
using Rake::TestTask
fixes #77
> New pbench feature

- lib/faster_path.rb
- lib/faster_path/optional/monkeypatches.rb
- lib/faster_path/optional/refinements.rb
- src/dirname.rs
- test/benches/dirname_benchmark.rb
- test/dirname_test.rb
- test/refinements/dirname_test.rb
- test/ripple_effects/cleanpath_aggressive_test.rb
- test/ripple_effects/cleanpath_conservative_test.rb
- test/ripple_effects/del_trailing_separator_test.rb
- test/ripple_effects/has_trailing_separator_test.rb
- test/ripple_effects/join_test.rb
- test/ripple_effects/plus_test.rb
I've implemented wrapper method for dirname and ported some tests from rubinius project.
Seems that some tests are failing(marked them in the code with #failing comment)
@danielpclark  Speaking about tests, should we fix the rust implementation or just fixt failing tests?
> Add FasterPath#dirname method and write some tests on it

- src/is_absolute.rs
- src/is_relative.rs
There seems to be a slight performance improvement with this PR (between 0.1% and 0.5%), but the `pbench` results vary wildly between the runs so not sure if statistically significant.
> Clean up is_absolute and is_relative

- lib/faster_path.rb
- lib/faster_path/optional/monkeypatches.rb
- lib/faster_path/optional/refinements.rb
- src/entries.rs
- src/lib.rs
- src/ruby_array.rs
- test/benches/entries_benchmark.rb
- test/entries_test.rb
- test/pbench/pbench_suite.rb
References #11.
Slower than the ruby one :(
@danielpclark if you have any optimisation in mind I'm all ears :)
> Naive entries implementation

- README.md
- lib/faster_path/optional/monkeypatches.rb
- lib/faster_path/optional/refinements.rb
- src/cleanpath_conservative.rs
- src/lib.rs
- src/pathname.rs
- test/benches/cleanpath_conservative_benchmark.rb
- test/cleanpath_conservative_test.rb
- test/pbench/pbench_suite.rb
> Cleanpath conservative

- README.md
- lib/faster_path/optional/monkeypatches.rb
- lib/faster_path/optional/refinements.rb
- src/helpers.rs
- src/lib.rs
- src/pathname.rs
- test/benches/del_trailing_separator_benchmark.rb
- test/benches/join_benchmark.rb
- test/del_trailing_separator_test.rb
- test/pbench/pbench_suite.rb
> Del trailing separator

- Cargo.lock
- Cargo.toml
- README.md
- lib/faster_path/optional/monkeypatches.rb
- lib/faster_path/optional/refinements.rb
- src/chop_basename.rs
- src/cleanpath_aggressive.rs
- src/cleanpath_conservative.rs
- src/debug.rs
- src/helpers.rs
- src/lib.rs
- src/pathname.rs
- src/pathname_sys.rs
- src/plus.rs
- src/relative_path_from.rs
- test/benches/relative_path_from_benchmark.rb
- test/pbench/pbench_suite.rb
- test/relative_path_from_test.rb
> Relative path from

- .rubocop.yml
- README.md
- faster_path.gemspec
- lib/faster_path/optional/monkeypatches.rb
- src/extname.rs
- src/path_parsing.rs
- test/basename_test.rb
- test/cleanpath_aggressive_test.rb
- test/cleanpath_conservative_test.rb
- test/del_trailing_separator_test.rb
- test/directory_test.rb
- test/dirname_test.rb
- test/extname_test.rb
- test/relative_test.rb
- test/test_helper.rb
> Windows tests

- README.md
https://travis-ci.org/danielpclark/faster_path/jobs/352146540
> Update Readme with the latest numbers [ci skip]

- src/cleanpath_aggressive.rs
- src/cleanpath_conservative.rs
- src/path_parsing.rs
- src/prepend_prefix.rs
Locally, I get:
* cleanpath_aggressive 71.7% -> 89.5%
* cleanpath_conservative 73.2% -> 90.9%
> Improve cleanpath* performance (71% -> 90%)

- src/chop_basename.rs
> Improve chop_basename performance (72.9% -> 75.6%)

- src/helpers.rs
- src/relative_path_from.rs
Locally: 88.7% -> 90.7%
Travis: [91.2%](https://travis-ci.org/danielpclark/faster_path/jobs/353111981) -> [93.4%](https://travis-ci.org/danielpclark/faster_path/jobs/353119848#L1020)
> Slightly faster relative_path_from (91.2% -> 93.4%)

- Cargo.lock
- Cargo.toml
- src/pathname.rs
- src/plus.rs
I'm not sure how well the tests verify correctness but they seem to pass.
Before: `join` 72.0%, `plus` 87.7%.
After: Pending long Travis run for performance results.
> Faster `plus` and `join`

- .appveyor.yml
- Cargo.lock
- Cargo.toml
- src/debug.rs
- src/helpers.rs
- src/lib.rs
- src/pathname.rs
- src/pathname_sys.rs
- src/relative_path_from.rs
Ruru & ruby-sys have been unmaintained for some time now.  I've taken on Rutie to maintain the work from these projects.
> Migrate from Ruru to Rutie
