danielpclark/faster_path

- README.md
- benches/bench.rs
- lib/faster_path.rb
- src/both_are_blank.rs
- src/lib.rs
- src/ruby_array.rs
- src/ruby_string.rs
- test/benches/chop_basename_benchmark.rb
An additional 19.2% performance gain has been added to
`FasterPath.chop_basename`.  This is the most called method in Rails
apps that I've seen.  With it's previous improvement of 27.5% my Rails
application performance improved by 15%.  So this is a huge performance
gain!
I've added more iterations to the benchmark test to try and get the
numbers tighter for more accurate benchmarks.
closes #5
> Improved speed of FasterPath.chop_basename again

- ext/faster_path/extconf.rb
Not sure if this fixes it for mac users, but I was having issues with getting this gem to install extensions inside a docker container running Debian Jessie. Switch to %x fixed it. Maybe something todo with waiting for output?
https://stackoverflow.com/questions/6338908/ruby-difference-between-exec-system-and-x-or-backticks
> Switch from system to %x for running rake in ext/faster_path/extconf.rb

- src/basename.rs
- src/basename_for_chop.rs
- src/both_are_blank.rs
- src/dirname.rs
- src/dirname_for_chop.rs
- src/is_absolute.rs
- src/is_blank.rs
- src/is_relative.rs
- src/lib.rs
- src/ruby_array.rs
- src/ruby_string.rs
std::include! is documented as ["this is generally a bad idea"](https://doc.rust-lang.org/std/macro.include!.html), mostly due to hygiene reasons. It's also unnecessary in this case, as Rust will happily export those symbols the way you want.
This patch removes the usage of include! and makes the files more self-contained, declaring their actual dependencies.
Weirdly though, I've hit a compiler bug in the process, you need to run `cargo test --release`, otherwise, the code won't compile in test mode. `cargo build --release` works fine.
> Remove usage of include! macro

- README.md
The line to install Rust includes sudo, but this is unnecessary. I've changed that line to exactly match the installation command given on rust-lang.org. This also involves removing the `-s -- channel=stable`, since this is implied by default.
> Installing Rust via rustup.sh doesn't require sudo

- README.md
- lib/faster_path.rb
- lib/faster_path/optional/monkeypatches.rb
- lib/faster_path/optional/refinements.rb
- src/add_trailing_separator.rs
- src/lib.rs
- test/add_trailing_separator_test.rb
- test/benches/add_trailing_separator_benchmark.rb
- test/monkeypatches/faster_path_test.rb
- test/refinements/add_trailing_separator_test.rb
* Implement Pathname.add_trailing_separator in Rust
* Hook Rust function into FasterPath as
FasterPath.add_trailing_separator
* Add FasterPath.add_trailing_separator monkeypatch and
refinement
* Add tests and benchmarks for FasterPath.add_trailing_separator
against Pathname.add_trailing_separator
https://github.com/danielpclark/faster_path/issues/43
> Add FasterPath.add_trailing_separator

- README.md
- lib/faster_path.rb
- lib/faster_path/optional/monkeypatches.rb
- lib/faster_path/optional/refinements.rb
- src/has_trailing_separator.rs
- src/lib.rs
- test/benches/has_trailing_separator_benchmark.rb
- test/has_trailing_separator_test.rb
- test/monkeypatches/faster_path_test.rb
- test/refinements/has_trailing_separator_test.rb
* Implement Pathname#has_trailing_separator? in Rust
* Hook Rust function into FasterPath as
FasterPath.has_trailing_separator?
* Add FasterPath.has_trailing_separator? monkeypatch and
refinement
* Add tests and benchmarks for FasterPath.has_trailing_separator?
against Pathname#has_trailing_separator?
https://github.com/danielpclark/faster_path/issues/49
> Add FasterPath.has_trailing_separator?

- lib/faster_path/optional/monkeypatches.rb
- lib/faster_path/optional/refinements.rb
- src/extname.rs
- test/benches/extname_benchmark.rb
- test/extname_test.rb
Also adds a commmented out test for a failing case NOT resolved by this PR.
```
$ rake pbench
Pinch-bench (Pbench) by Daniel P. Clark
64-bit ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]
64-bit rustc 1.9.0 (e4e8b6668 2016-05-18)
Performance change for allocate, instead of new, is 80.6%
Performance change for absolute? is 92.8%
Performance change for add_trailing_separator is 55.4%
Performance change for basename is 1.3%
Performance change for chop_basename is 22.3%
Performance change for directory? is 32.8%
Performance change for extname is 49.6%
Performance change for has_trailing_separator? is 45.8%
Performance …
```
> Fixes a couple of extname edge cases

- lib/faster_path/optional/monkeypatches.rb
- lib/faster_path/optional/refinements.rb
- src/basename.rs
- test/basename_test.rb
More idiomatic, slightly faster, extracted from #66 
```
$  WITH_REGRESSION=1 rake pbench
Pinch-bench (Pbench) by Daniel P. Clark
64-bit ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]
64-bit rustc 1.9.0 (e4e8b6668 2016-05-18)
Performance change for allocate, instead of new, is 80.1%
Performance change for absolute? is 92.8%
Performance change for add_trailing_separator is 55.3%
Performance change for basename is 6.3%
Performance change for chop_basename is 26.6%
Performance change for directory? is 32.6%
Performance change for extname is 51.1%
Performance change for has_trailing_separator? is 52.1%
Performance change …
```
> basename: Improve performance and style

- src/extname.rs
- test/extname_test.rb
Fixes the last non-encoding/`#to_path`/TypeError related extname edge case.
However, this is a bit slower than the current impl :(
```
$ WITH_REGRESSION=1 rake pbench
Pinch-bench (Pbench) by Daniel P. Clark
64-bit ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]
64-bit rustc 1.9.0 (e4e8b6668 2016-05-18)
Performance change for allocate, instead of new, is 80.9%
Performance change for absolute? is 92.9%
Performance change for add_trailing_separator is 55.6%
Performance change for basename is 6.2%
Performance change for chop_basename is 30.1%
Performance change for directory? is 41.0%
Performance change for extname is 35.5% …
```
> Fix extname edge case

- README.md
- Rakefile
Reduces the amount of steps required for someone to start developing, by explicitly requiring `build_lib` to be run before any of the test tasks.
Also did some cleanup while I was in there.
> Reduce development setup

- benches/path_parsing.rs
- benches/rust_ruby.rs
- src/basename.rs
- src/dirname.rs
- src/extname.rs
- src/lib.rs
- src/path_parsing.rs
Benches several ways of working with paths at low level.
Changes the methods to use the fastest approach.
```
$ rake pbench
Building extension...
Compiling libc v0.2.11
Compiling faster_path v0.0.1 (file:///home/glebm/repos/glebm/faster_path)
Cleaning up build...
Completed build!
Pinch-bench (Pbench) by Daniel P. Clark
64-bit ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]
64-bit rustc 1.11.0-nightly (ad7fe6521 2016-06-23)
Performance change for allocate, instead of new, is 80.6%
Performance change for absolute? is 92.4%
Performance change for add_trailing_separator is 54.4%
Performance change for basename is 4.7% …
```
> Faster basename, dirname, extname

- faster_path.gemspec
These are more than mere development dependencies.
> May influence #18, #20, and #68

- .gitignore
- .gitmodules
- Gemfile
- README.md
- Rakefile
- lib/faster_path/optional/monkeypatches.rb
- lib/faster_path/optional/refinements.rb
- spec/default.mspec
- spec/init.rb
Adds The Ruby Spec Suite as a submodule and configures for running with the FasterPath monkey patches.
> Test with The Ruby Spec Suite

- Rakefile
before 
```
➜  faster_path git:(master) ✗ rake build_src
Building extension...
➜  faster_path git:(master) ✗ echo $?
0
```
after
```
➜  faster_path git:(fail-rake-task-if-shell-failed) ✗ rake build_src
Building extension...
cargo build --release
rake aborted!
Command failed with status (127): [cargo build --release...]
faster_path/Rakefile:8:in `block in <top (required)>'
Tasks: TOP => build_src
(See full trace by running task with --trace)
➜  faster_path git:(fail-rake-task-if-shell-failed) ✗ echo $?
1
```
> Fail rake task if shell failed

- lib/faster_path.rb
- lib/faster_path/asset_resolution.rb
- test/asset_resolution_test.rb
> If rust asset not available raise error.

- README.md
- lib/faster_path.rb
- lib/faster_path/optional/monkeypatches.rb
- lib/faster_path/optional/refinements.rb
- lib/faster_path/version.rb
- src/lib.rs
- src/pathname.rs
- test/benches/children_benchmark.rb
- test/children_test.rb
- test/faster_pathname.rb
- test/pbench/pbench_suite.rb
Comments for next methods to be implemented added.
Methods moved out of ruru's `methods!` macro for future instance variable referencing private methods.
Directory parsing methods do less iterations during pinch benchmark suite.
Prep work for FasterPathname to be drop in replacement for Pathname.  Note: The C methods will be mapped to directly in the future through Rust calls through ruby-sys.
Fixes #114
> Children method & re-org methods

- .rubocop.yml
- .rustfmt.toml
- Cargo.lock
- Cargo.toml
- Rakefile
- faster_path.gemspec
- lib/faster_path.rb
- lib/faster_path/optional/monkeypatches.rb
- lib/faster_path/optional/refinements.rb
- src/helpers.rs
- src/lib.rs
- src/pathname.rs
- test/benches/children_compat_benchmark.rb
- test/benches/entries_compat_benchmark.rb
- test/children_test.rb
- test/entries_test.rb
- test/monkeypatches/faster_path_test.rb
- test/output_type_compatibility_test.rb
- test/pbench/pbench.rb
- test/pbench/pbench_suite.rb
- test/test_helper.rb
* Build compat methods for `entries` and `children`.
* Comment them out as ruru has a segfault for them
* Add a central test file for output compatibility
* Ruby 2.4.2 is wanky so disable monkeypatch tests for that version because of require `method_source` error.  Also switched away from `method_source` gem to `read_source` as it is much smaller, I control it, and perhaps can find a fix for it… note issue still exists in Ruby 2.4.2.
* Update rubocop namespaces
* Add rustfmt preferred styles (not applied)
* Reduce coveralls tests on CI from two to one
* Add pinch benchmark to CI test suite run as the potential ruru segfault issue only occurs occasionally (https://github.com/d-unseductable/ruru/issues/75) .  So until ruru is fixed we need to guard against the possibility of occasional …
> Compat methods

- Cargo.lock
- Cargo.toml
- src/helpers.rs
- Use ruru API instead of unsafe ruby-sys API for type conversions
- Remove the explicit ruby-sys dependency from `Cargo.toml`
> Refactor helpers module

- src/extname.rs
- src/pathname.rs
- Use `&str` instead of `String` for `extname::extname`
I've done several passes of `pbench`, it shows the following performance change for `extname`:
- on `master`, from -5% to 12%;
- on this branch, from 26% to 37%.
> Do not allocate Strings in extname

- lib/faster_path.rb
- src/lib.rs
- test/children_test.rb
- test/entries_test.rb
- test/output_type_compatibility_test.rb
- Define class methods instead of instance methods for `FasterPathname::Public`
- Do not use `Public.allocate`
Resolves #131.
> Refactor out use of allocate

- Cargo.lock
- Cargo.toml
- src/basename.rs
- src/dirname.rs
- src/lib.rs
- src/path_parsing.rs
- src/pathname.rs
- src/plus.rs
Before: Performance change for basename is -97.7%
After replacing with `bytes()`: -34.5%
After avoiding iteration for the edge check: -30.8%
After returning `&str` instead of String: -25.8%
After using `memrchr` instead of `rfind`: -20%
`dirname` also went from -7% to +7%
Refs #130
> Optimize basename and dirname

- src/prepend_prefix.rs
Performance change for:
* cleanpath_aggressive 69.6% -> 73.0%
* cleanpath_conservative 72.7% -> 73.7%
Note that the `cleanpath*` functions still do *a lot* of unnecessary heap allocations  via `to_string()`.
> Reduce allocations in `prepend_prefix`

- lib/faster_path/optional/monkeypatches.rb
- src/basename.rs
- src/dirname.rs
- src/lib.rs
- src/memrnchr.rs
- src/path_parsing.rs
- test/benches/dirname_benchmark.rb
A faster and more readable implementation of `basename` and `dirname`.
> Improve `basename` and `dirname`

- src/memrnchr.rs
The bytes check was incorrect, leading to bugs in some cases.
> Fix a bug in memrnchr

- src/helpers.rs
- src/pathname.rs
- src/relative_path_from.rs
1. Avoids unnecessary String allocations.
2. Reserve Array capacity when possible.
3. Avoid `Char` in favour of `u8` when possible.
4. `.ok().unwrap` -> `.unwrap`.
Travis benchmark:
Before: https://travis-ci.org/danielpclark/faster_path/jobs/352457728
```
64-bit ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-linux]
64-bit rustc 1.24.1 (d3ae9a9e0 2018-02-27)
architecture: x86_64-unknown-linux-gnu
Performance change for allocate, instead of new, is 77.5%
Performance change for absolute? is 88.5%
Performance change for add_trailing_separator is 39.3%
Performance change for basename is 1.8%
Performance change for children is 43.5%
Performance change for children_compat is -56.7%
Performance change for …
```
> Various performance improvements to pathname

- src/basename.rs
- src/path_parsing.rs
Fixes #162 
This incorporates all the Rust tests added by @danielpclark's in #163 and adds a few more. There does not seem to be any noticable performance impact.
> Fixes the basename .. bug

- Cargo.lock
- Rakefile
- lib/faster_path.rb
- lib/faster_path/optional/monkeypatches.rb
- lib/faster_path/optional/refinements.rb
- lib/faster_path/thermite_initialize.rb
Applied changes upstream as Andrew suggested in #143 .  Now rake doesn't need to copy Ruby's lib for Rust code to work.  Don't even need a feature flag.
> Changed ruby-sys & ruru. libruby copy not required
